# -*- coding: utf-8 -*-
"""module.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B5DQ_Ch61cLRDMlaqn0UlWfuU7JPerdg

#Module
A module is a file that contains python code that we can use in our program
"""

def greetings():
  print("Hi! BSCE101E was an awesome class!!!!")

"""#Build-in modules

1. math
2. datetime
3. functools
random
pathlib

"""